CREATE TABLE loan_funding (
                              id SERIAL PRIMARY KEY,                                        -- Funding ID
                              loan_order_number VARCHAR(50) NOT NULL,                        -- Loan order number (generated by the system)
                              order_number VARCHAR(50) NOT NULL,                             -- Loan order number generated when lender funds the loan
                              loan_id INT,                                                  -- Loan ID, linked to the loans table
                              lender_id INT,                                                -- Lender ID
                              lender_email VARCHAR(255),                                     -- Lender email address
                              investment_amount DECIMAL(15, 2),                              -- Investment amount
                              rate DECIMAL(5, 2),                                            -- Interest rate
                              interest DECIMAL(15, 2),                                       -- Interest amount
                              roi DECIMAL(15, 2),                                             -- Return on Investment (ROI)
                              interest_paid DECIMAL(15, 2) DEFAULT 0.00,                     -- Total interest paid so far
                              capital_amount_paid DECIMAL(15, 2) DEFAULT 0.00,               -- Total capital (principal) paid so far
                              total_amount_paid DECIMAL(15, 2) DEFAULT 0.00,                 -- Total amount (capital + interest) paid so far
                              investment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,           -- Investment date
                              status VARCHAR(50),                                            -- Investment status (e.g., 'invested', 'on_going', 'completed')
                              lender_agreement_url VARCHAR(255),                             -- Lender agreement URL, uploaded to the cloud
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                -- Date of funding record creation
                              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,                -- Date of funding record update
                              deleted_at TIMESTAMP DEFAULT NULL                   -- Date of document record deletion (if applicable)
);
