version: "3.9"
    
services:
  pg:
    container_name: db-loan-service
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    networks:
      - test-network

networks:
  test-network:
    external: true